import os
import sys
import importlib
import pkgutil
import re

try:
    import openpyxl
except ImportError:
    print("[export_tables] 缺少 openpyxl，请执行: pip install openpyxl")
    sys.exit(1)

from table_exporter import TableDef


def _convert(val, typ):
    if val is None:
        if typ is str:
            return ""
        if typ is int:
            return 0
        if typ is float:
            return 0.0
        if typ is bool:
            return False
        return val
    if typ is str:
        return str(val)
    if typ is int:
        if isinstance(val, bool):
            raise TypeError(f"无法将 bool 值转换为 int: '{val}'")
        try:
            return int(str(val).strip())
        except (ValueError, TypeError):
            raise TypeError(f"无法转换为 int: '{val}'")
    if typ is float:
        try:
            return float(str(val).strip())
        except (ValueError, TypeError):
            raise TypeError(f"无法转换为 float: '{val}'")
    if typ is bool:
        if isinstance(val, bool):
            return val
        if isinstance(val, (int, float)):
            return val != 0
        s = str(val).strip().lower()
        if s in ("true", "1", "是", "yes", "t"):
            return True
        if s in ("false", "0", "否", "no", "f", ""):
            return False
        raise TypeError(f"无法转换为 bool: '{val}'")
    return val


def _repr(val):
    if isinstance(val, str):
        return repr(val)
    return str(val)


def _find_key_type(config):
    for src, dest, typ in config.fields:
        if dest == config.key:
            return typ
    return None


def export_single(config):
    source_path = config.source
    if not os.path.isfile(source_path):
        print(f"[export_tables] 错误: 源文件不存在 '{source_path}'（来自配置 '{config.name}'）")
        sys.exit(1)

    wb = openpyxl.load_workbook(source_path, read_only=True, data_only=True)

    if config.sheet:
        if config.sheet not in wb.sheetnames:
            print(f"[export_tables] 错误: '{source_path}' 中找不到 Sheet '{config.sheet}'")
            print(f"  可用 Sheet: {wb.sheetnames}")
            sys.exit(1)
        ws = wb[config.sheet]
    else:
        ws = wb.active

    rows = list(ws.iter_rows(values_only=True))
    if not rows:
        print(f"[export_tables] 错误: '{source_path}' Sheet '{ws.title}' 为空")
        sys.exit(1)

    headers = [str(h) if h is not None else "" for h in rows[0]]

    col_map = {}
    for src, dest, typ in config.fields:
        if src in headers:
            col_map[dest] = (headers.index(src), typ)
        else:
            print(f"[export_tables] 错误: 在 '{source_path}' Sheet '{ws.title}' 中找不到列 '{src}'")
            sys.exit(1)

    key_type = _find_key_type(config)
    if key_type is None:
        print(f"[export_tables] 错误: 配置中 key='{config.key}' 未在 fields 中找到")
        sys.exit(1)

    key_src = None
    for src, dest, typ in config.fields:
        if dest == config.key:
            key_src = src
            break
    key_col_idx = headers.index(key_src)

    result = {}
    for row_idx, row in enumerate(rows[1:], start=2):
        if all(cell is None for cell in row):
            continue

        key_raw = row[key_col_idx]
        if key_raw is None:
            print(f"[export_tables] 错误: '{source_path}' Sheet '{ws.title}' 第 {row_idx} 行主键为空")
            sys.exit(1)

        key_val = _convert(key_raw, key_type)

        dup_key = _repr(key_val)
        if key_val in result:
            print(f"[export_tables] 错误: '{source_path}' Sheet '{ws.title}' 第 {row_idx} 行主键重复: {dup_key}")
            sys.exit(1)

        item = {}
        for dest_name, (col_idx, typ) in col_map.items():
            raw = row[col_idx]
            try:
                item[dest_name] = _convert(raw, typ)
            except TypeError as e:
                col_name = headers[col_idx]
                print(f"[export_tables] 错误: '{source_path}' Sheet '{ws.title}' 第 {row_idx} 行列 '{col_name}': {e}")
                sys.exit(1)

        for validator in config._validators:
            try:
                validator(item)
            except AssertionError as e:
                print(f"[export_tables] 校验失败: '{source_path}' Sheet '{ws.title}' 第 {row_idx} 行 key={dup_key}: {e}")
                sys.exit(1)
            except Exception as e:
                print(f"[export_tables] 校验异常: '{source_path}' Sheet '{ws.title}' 第 {row_idx} 行 key={dup_key}: {e}")
                sys.exit(1)

        result[key_val] = item

    return result


def gen_py(config, data):
    lines = [
        "# Auto-generated by export_tables.py - DO NOT EDIT",
        f"# Source: {config.source}",
        "" if not config.sheet else f"# Sheet: {config.sheet}",
        "",
        f"{config.name} = {{",
    ]
    for key, row in data.items():
        fields_str = ", ".join(f"{_repr(k)}: {_repr(v)}" for k, v in row.items())
        lines.append(f"    {_repr(key)}: {{{fields_str}}},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def discover_defs():
    defs_dir = os.path.join(os.getcwd(), "scripts", "tables", "defs")
    sys.path.insert(0, os.path.join(os.getcwd(), "scripts"))

    import tables.defs as defs_pkg

    found = []
    for mod_info in pkgutil.iter_modules(defs_pkg.__path__):
        if mod_info.name.startswith("_"):
            continue
        mod = importlib.import_module(f"tables.defs.{mod_info.name}")
        for attr_name in dir(mod):
            obj = getattr(mod, attr_name)
            if isinstance(obj, TableDef):
                found.append(obj)
    return found


def main():
    print("[export_tables] 开始导出配表...")

    configs = discover_defs()
    if not configs:
        print("[export_tables] 未发现任何配表配置")
        return

    output_dir = os.path.join(os.getcwd(), "scripts", "tables", "data")

    for cfg in configs:
        print(f"  [{cfg.name}] 导出中...")
        data = export_single(cfg)
        code = gen_py(cfg, data)
        out_path = os.path.join(output_dir, f"{cfg.name}.py")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(code)
        print(f"    -> 已生成 {out_path} ({len(data)} 行)")

    print("[export_tables] 全部导出完成")


if __name__ == "__main__":
    main()
